dist: bionic

language: go
go:
  - 1.13.4

services:
  - docker

env:
  global:
    - IMG_NAME=daocasino/casinoback
    - IMG_TAG=${TRAVIS_TAG:-${TRAVIS_BRANCH}-${TRAVIS_COMMIT:0:5}}

environments:
  - &DEV_ENV
    - AWS_DEFAULT_REGION=${DEV_AWS_REGION}
    - AWS_ACCESS_KEY_ID=${DEV_AWS_ACCESS_KEY_ID}
    - AWS_SECRET_ACCESS_KEY=${DEV_AWS_SECRET}

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

cache:
  directories:
    - $HOME/.ccache
  timeout: 1000

git:
  depth: false

notifications:
  email: false

before_script:
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $GOPATH/bin v1.23.1

jobs:
  include:
    - stage: lint & test
      script:
        - golangci-lint run --skip-files 'test'
        - go test -v -race -coverprofile=coverage.txt -covermode=atomic .
    - stage: build & push
      script:
       - docker build -t $IMG_NAME:$IMG_TAG .
       - docker push $IMG_NAME:$IMG_TAG
    - stage: deploy
      env:
        - *DEV_ENV
      script:
        |
        if [[ "$TRAVIS_PULL_REQUEST" == "false" && "$TRAVIS_BRANCH" == "develop" ]]; then
          docker run -e AWS_DEFAULT_REGION -e AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY silintl/ecs-deploy -t 300 -c platform-dev -n casino -i $IMG_NAME:$IMG_TAG --skip-deployments-check
        fi

after_success:
  - bash <(curl -s https://codecov.io/bash)
