[server]
port = 6565
logLevel = "debug"

[broker]
topicOffsetPath = "offset.txt"
url = "localhost:8889"
topicID = 0
token = "secretToken"

[blockchain]
depositkey = "5JJvavvETHcGEx7ueoDry8zvcfPenbBCKcUQXXXXXX"
signidicekey = "5JJvavvETHcGEx7ueoDry8zvcfPenbBCKcUQXXXXXX"
rsakey = "base64 encoded pem key"
url = "https://api.daobet.org"
casinoAccountName = "daocasinoxxx"
platformAccountName = "platform"
platformPubKey = "EOS1234"
chainID = "cda75f235aef76ad91ef0503421514d80d8dbb584cd07178022f0bc7deb964ff"

[http]
retrydelay = 1
retryamount = 3
timeout = 3
